name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  django-tests:
    name: Django Tests
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: talana.settings_test
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: app
        run: pip install -r requirements.txt
      - name: Run tests
        working-directory: app
        run: python manage.py test

  dockerfile-lint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: app/Dockerfile
          config: .hadolint.yaml

  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: "~1.10"
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -backend=false
      - name: Terraform Format Check
        working-directory: terraform
        run: terraform fmt -check -recursive
      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate
      - name: Terraform Init Bootstrap
        working-directory: terraform/bootstrap
        run: terraform init -backend=false
      - name: Terraform Validate Bootstrap
        working-directory: terraform/bootstrap
        run: terraform validate

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [django-tests, dockerfile-lint]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Build Docker image
        run: docker build -t django:${{ github.sha }} app/
